CREATE TABLE "s3_schemas"."flight_fact"(airline_key         bigint encode az64,
                                        origin_airport_key  bigint encode az64,
                                        plane_key           bigint encode az64,
                                        dest_airport_key    bigint encode az64,
                                        actual_dep_time_key integer encode az64,
                                        flight_date_key     integer encode az64,
                                        cancelled           double precision,
                                        diverted            double precision,
                                        arr_time            double precision,
                                        dep_time            double precision,
                                        wheels_off          double precision,
                                        wheels_on           double precision,
                                        weather_delay       double precision,
                                        nas_delay           double precision,
                                        security_delay      double precision,
                                        late_aircraft_delay double precision,
                                        total_delay         double precision,
                                        taxi_in             double precision,
                                        taxi_out            double precision,
                                        div1_airport_key    bigint encode az64,
                                        div1_plane_key      bigint encode az64,
                                        div1_wheels_off     double precision,
                                        div1_wheels_on      double precision,
                                        div2_airport_key    bigint encode az64,
                                        div2_plane_key      bigint encode az64,
                                        div2_wheels_off     double precision,
                                        div2_wheels_on      double precision);